name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # Allows to manually run the job at any time
  workflow_dispatch:
  
  # Run on every push to the master branch
  push:
    branches:
      - main  # Alterado para `main`

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generates a snake game from a GitHub user’s contributions graph, outputs an SVG animation
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: cancellap  # Altere para o seu nome de usuário
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Push the content of `dist` directory to the `main` branch
      - name: push github-contribution-grid-snake.svg to the main branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main  # Alterado para `main`
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
