name: Atualizar README com cache bust

on:
  schedule:
    - cron: '0 6 * * *' # Executa todo dia às 6h UTC
  workflow_dispatch:     # Permite executar manualmente pelo GitHub Actions

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Atualizar parâmetro da imagem
        run: |
          V=$(date +%s)
          sed -i "s|https://github-readme-stats.vercel.app/api/top-langs?username=cancellap.*|https://github-readme-stats.vercel.app/api/top-langs?username=cancellap&layout=compact&langs_count=8&card_width=320&show_icons=true&theme=dracula&v=$V|" README.md
      
      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add README.md
          git commit -m "Atualiza imagem README com cache bust" || echo "Sem alterações"
          git push

